modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="apothic_attributes"

version="2.3.0"

displayName="Apothic Attributes"

authors="Shadows_of_Fire"

description='''A library mod providing Attributes and related things.'''

[[mixins]]
config="apothic_attributes.mixins.json"

[[dependencies.apothic_attributes]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_attributes]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_attributes]]
    modId="placebo"
    type="required"
    versionRange="[9.4.1,)"
    ordering="AFTER"
    side="BOTH"
